name: Reusable Workflow Caller

on:
  push:

jobs:
  Reusable-caller-job:
    uses: ./.github/workflows/maven-cache.yml
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
